import { StyleSheet } from "react-native";
import {
  colors,
  radius,
  spacing,
  touchTarget,
  typography,
} from "@grownupsvet/accessibility-kit";

export const petStyles = StyleSheet.create({
  flex: { flex: 1, backgroundColor: colors.background },
  container: { padding: spacing.lg, gap: spacing.md },
  topBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: spacing.sm,
  },
  title: {
    fontSize: typography.heading,
    fontWeight: "600",
    color: colors.text,
  },
  backButton: {
    minHeight: touchTarget.minimum,
    justifyContent: "center",
  },
  backLabel: {
    fontSize: typography.body,
    color: colors.accent,
    fontWeight: "500",
  },
  primaryButton: {
    minHeight: touchTarget.comfortable,
    backgroundColor: colors.accent,
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
  },
  primaryButtonLabel: {
    fontSize: typography.bodyLarge,
    fontWeight: "600",
    color: colors.onAccent,
  },
  secondaryButton: {
    minHeight: touchTarget.comfortable,
    backgroundColor: colors.surfaceAlt,
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
  },
  secondaryButtonLabel: {
    fontSize: typography.bodyLarge,
    fontWeight: "600",
    color: colors.text,
  },
  dangerButton: {
    minHeight: touchTarget.comfortable,
    backgroundColor: colors.danger,
    borderRadius: radius.md,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.lg,
  },
  dangerButtonLabel: {
    fontSize: typography.bodyLarge,
    fontWeight: "600",
    color: colors.onDanger,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    gap: spacing.sm,
  },
  cardTitle: {
    fontSize: typography.title,
    fontWeight: "600",
    color: colors.text,
  },
  cardSubtitle: {
    fontSize: typography.body,
    color: colors.textSecondary,
  },
  archivedBadge: {
    alignSelf: "flex-start",
    backgroundColor: colors.warningBackground,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  archivedBadgeLabel: {
    fontSize: typography.caption,
    fontWeight: "600",
    color: colors.warning,
  },
  row: { flexDirection: "row", gap: spacing.sm },
  field: { gap: spacing.xs },
  label: { fontSize: typography.body, fontWeight: "500", color: colors.text },
  input: {
    minHeight: touchTarget.comfortable,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    fontSize: typography.body,
    color: colors.text,
    backgroundColor: colors.surface,
  },
  helperText: { fontSize: typography.caption, color: colors.textMuted },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: spacing.xs,
  },
  detailLabel: { fontSize: typography.body, color: colors.textSecondary },
  detailValue: {
    fontSize: typography.body,
    color: colors.text,
    fontWeight: "500",
  },
  segmentedRow: { flexDirection: "row", gap: spacing.sm },
  segmentButton: {
    flex: 1,
    minHeight: touchTarget.comfortable,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: "center",
    justifyContent: "center",
  },
  segmentButtonActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  segmentButtonLabel: {
    fontSize: typography.body,
    color: colors.text,
    fontWeight: "500",
  },
  segmentButtonLabelActive: { color: colors.onAccent },
});
